# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f9308dc6d13fa001b0a378a3ff13dd4510af041f027ce1abc97ff9f40fd9d6e7fbd6865522bc1f5b9c2f83bda45b1e4ded42477a83aa8e35fb8f1b9ecfdc06a

test:
  secret_key_base: 79a52d4858924920c8724df62ad326bde70c72ccccbdfbf974e99e38480c1dd548f37128fea71ab19513f6eaceb73c8f6f6d1bb369b5d321d67ad6afc2a1c28f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
